api = "0.7"

[buildpack]
  description = "A buildpack for configuring and running HTTPD for PHP apps"
  homepage = "https://github.com/initializ-buildpacks/php-httpd"
  id = "initializ-buildpacks/php-httpd"
  keywords = ["php", "httpd"]
  name = "Initializ Buildpack for PHP HTTPD"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/initializ-buildpacks/php-httpd/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "*"
